# 1.Интерполяция Лагранжа

In [57]:
import numpy as np

In [58]:
import scipy.integrate

In [59]:
from scipy.interpolate import lagrange

In [60]:
x = np.array([0,1,2])
y = np.array([0,1,2])

In [61]:
lagrange(x,y)

poly1d([1., 0.])

# $$y=x$$

In [62]:
x = np.array([0.5,0.6,0.8,1])
y = np.array([-0.229,-0.205,-0.077,0.159])
lagrange(x,y)

poly1d([ 0.03333333,  1.27      , -1.18733333,  0.043     ])

# $$y=0.0333x^3+1.27x^2-1.18733x+0.043$$

In [63]:
lagrange(x,y)(1)

0.15900000000000725

# 2.Численное интегрирование

Попробуем проинтегрировать симпсона из моей домашки

# $$f(x)=|cos(sin(x))-3/4|$$

## 1. В общем случае пишем питоновскую функцию нашей функции

In [64]:
def f(x):
    answer=abs(np.cos(np.sin(x))-3/4)
    return answer

## 2. Немного магии из _numpy_

In [65]:
N=30 #Количетсво отрезков

In [66]:
x=[0]

In [67]:
for i in range(0,N):
    x.append(x[i]+np.pi/N)

In [68]:
x

[0,
 0.10471975511965977,
 0.20943951023931953,
 0.3141592653589793,
 0.41887902047863906,
 0.5235987755982988,
 0.6283185307179586,
 0.7330382858376184,
 0.8377580409572782,
 0.942477796076938,
 1.0471975511965979,
 1.1519173063162575,
 1.2566370614359172,
 1.361356816555577,
 1.4660765716752366,
 1.5707963267948963,
 1.675516081914556,
 1.7802358370342157,
 1.8849555921538754,
 1.9896753472735351,
 2.094395102393195,
 2.1991148575128547,
 2.3038346126325147,
 2.4085543677521746,
 2.5132741228718345,
 2.6179938779914944,
 2.7227136331111543,
 2.8274333882308142,
 2.932153143350474,
 3.036872898470134,
 3.141592653589794]

In [69]:
len(x)

31

In [70]:
f(x)

array([0.25      , 0.24454187, 0.22846411, 0.20263298, 0.16841674,
       0.12758256, 0.08217084, 0.03436125, 0.01365561, 0.05978992,
       0.10214066, 0.13905725, 0.16917662, 0.19144   , 0.20509616,
       0.20969769, 0.20509616, 0.19144   , 0.16917662, 0.13905725,
       0.10214066, 0.05978992, 0.01365561, 0.03436125, 0.08217084,
       0.12758256, 0.16841674, 0.20263298, 0.22846411, 0.24454187,
       0.25      ])

In [71]:
y=f(x) #Загоняем значения функции в массив игриков

In [72]:
scipy.integrate.simps(y,x) 

0.4611341556247767

## Здесь следующий подводные - чекните какая версия скайпая у вас установлена, потому что в один момент функцию simps переимениовали в simpsons или типа того. Самое простое - попробуйте повызывать эти функции в своем питоне

In [73]:
scipy.integrate.simpsons(y,x)

AttributeError: module 'scipy.integrate' has no attribute 'simpsons'

In [75]:
scipy.__version__

'1.4.1'

Если у вас здесь цифра больше 1.5 или типа того(я не уточнял), то у вас будет функция называется __simpsons__

## Интегрирование трапецией

In [76]:
scipy.integrate.trapz(y,x)

0.460426672049548

Здесь аналогично в новых версиях метод называется trapezoid, вообще смотрите здесь
https://docs.scipy.org/doc/scipy/reference/integrate.html

# 3.Гаусс Картофель

Попробуем посчитать вариантик который нам показывали на консультации (весовая функция синий синус)

## Сначала учимся интегрировать $\int_{0}^{\pi }x^n\cdot sin(x)$

In [77]:
I=[0,1,2,3]

В функцию засуну лямбда функцию, которая возвращает $x^n \cdot \sin(x)$ числа и прошу проинтегрировать от нуля до пи, затем добавляю в наш массив чтобы потом найти коэффициенты для Гауса картофеля

In [78]:
I[0]=scipy.integrate.quad(lambda x:np.sin(x),0,np.pi)[0]
I[0]

2.0

На семинаре 2

In [79]:
I[1]=scipy.integrate.quad(lambda x: x*np.sin(x),0,np.pi)[0]
I[1]

3.141592653589793

На семинаре $\pi$

In [80]:
I[2]=scipy.integrate.quad(lambda x: x*x*np.sin(x),0,np.pi)[0]
I[2]

5.869604401089359

На семинаре $\pi^2-4$

In [81]:
np.pi*np.pi-4

5.869604401089358

Совпадает. Считаем последний интеграл :

In [82]:
I[3]=scipy.integrate.quad(lambda x: x*x*x*np.sin(x),0,np.pi)[0]
I[3]

12.15672075876106

In [83]:
np.pi*np.pi*np.pi-6*np.pi

12.156720758761058

Блин внатуре реально магические приколы какие-то

Итого

In [84]:
I

[2.0, 3.141592653589793, 5.869604401089359, 12.15672075876106]

## Теперь попробуем влезть в наш солвер, солвать будем scipy.fsolve(бебебе)

In [85]:
def func(variables):
    (w0,w1,x0,x1)=variables
    eqn_1=w0+w1-I[0]
    eqn_2=w0*x0+w1*x1-I[1]
    eqn_3=w0*x0*x0+w1*x1*x1-I[2]
    eqn_4=w0*x0*x0*x0+w1*x1*x1*x1-I[3]
    return [eqn_1,eqn_2,eqn_3,eqn_4]

In [86]:
answer=scipy.optimize.fsolve(func,[1,1,-1,1])
answer

array([1.        , 1.        , 0.88712894, 2.25446372])

In [87]:
func(answer)

[0.0, -1.213251721310371e-12, -2.574829238710663e-12, -3.998579245489964e-12]

In [88]:
I=[2,0,2/3,0]

In [89]:
def func(variables):
    (w0,w1,x0,x1)=variables
    eqn_1=w0+w1-I[0]
    eqn_2=w0*x0+w1*x1-I[1]
    eqn_3=w0*x0*x0+w1*x1*x1-I[2]
    eqn_4=w0*x0*x0*x0+w1*x1*x1*x1-I[3]
    return [eqn_1,eqn_2,eqn_3,eqn_4]

In [91]:
scipy.optimize.fsolve(func,[1,1,1,1])

array([-1.77331406,  3.77355461, -0.03148095, -0.02671432])

## Этот солвер не работает, он вычматами считает, скажите пж что здесь не так, я здесь под переменными имею ввиду $\omega_0=x[0],\omega_1=x[1],x_0=x[2],x_1=x[3]$

# В качестве солвера используем вольфрам пацаны