# 1.Интерполяция Лагранжа

In [4]:
import numpy as np

In [5]:
from scipy.interpolate import lagrange

In [6]:
x = np.array([0,1,2])
y = np.array([0,1,2])

In [7]:
lagrange(x,y)

poly1d([1., 0.])

# $$y=x$$

In [8]:
x = np.array([0.5,0.6,0.8,1])
y = np.array([-0.229,-0.205,-0.077,0.159])
lagrange(x,y)

poly1d([ 0.03333333,  1.27      , -1.18733333,  0.043     ])

# $$y=0.0333x^3+1.27x^2-1.18733x+0.043$$

In [13]:
lagrange(x,y)(1)

0.15900000000000725

# 2.Численное интегрирование

Попробуем проинтегрировать симпсона из моей домашки

# $$f(x)=|cos(sin(x))-3/4|$$

## 1. В общем случае пишем питоновскую функцию нашей функции

In [14]:
def f(x):
    answer=abs(np.cos(np.sin(x))-3/4)
    return answer

## 2. Немного магии из _numpy_

In [78]:
N=30 #Количетсво отрезков

In [79]:
x=np.arange(0,np.pi,np.pi/N) #Разбиваем промежуток от 0 до пи на N отрезков

In [80]:
x 

array([0.        , 0.10471976, 0.20943951, 0.31415927, 0.41887902,
       0.52359878, 0.62831853, 0.73303829, 0.83775804, 0.9424778 ,
       1.04719755, 1.15191731, 1.25663706, 1.36135682, 1.46607657,
       1.57079633, 1.67551608, 1.78023584, 1.88495559, 1.98967535,
       2.0943951 , 2.19911486, 2.30383461, 2.40855437, 2.51327412,
       2.61799388, 2.72271363, 2.82743339, 2.93215314, 3.0368729 ])

In [81]:
f(x)

array([0.25      , 0.24454187, 0.22846411, 0.20263298, 0.16841674,
       0.12758256, 0.08217084, 0.03436125, 0.01365561, 0.05978992,
       0.10214066, 0.13905725, 0.16917662, 0.19144   , 0.20509616,
       0.20969769, 0.20509616, 0.19144   , 0.16917662, 0.13905725,
       0.10214066, 0.05978992, 0.01365561, 0.03436125, 0.08217084,
       0.12758256, 0.16841674, 0.20263298, 0.22846411, 0.24454187])

In [82]:
y=f(x) #Загоняем значения функции в массив игриков

In [83]:
scipy.integrate.simps(y,x) 

0.4343445840617907

## Здесь следующий подводные - чекните какая версия скайпая у вас установлена, потому что в один момент функцию simps переимениовали в simpsons или типа того. Самое простое - попробуйте повызывать эти функции в своем питоне

In [87]:
scipy.inegrate.simpsons(y,x)

AttributeError: module 'scipy' has no attribute 'inegrate'

In [85]:
scipy.__version__

'1.4.1'

Если у вас здесь цифра больше 1.5 или типа того(я не уточнял), то у вас будет функция называется __simpsons__

## Интегрирование трапецией

In [88]:
scipy.integrate.trapz(y,x)

0.43453252015119537

Здесь аналогично в новых версиях метод называется trapezoid, вообще смотрите здесь
https://docs.scipy.org/doc/scipy/reference/integrate.html

# 3.Гаусс Картофель

Попробуем посчитать вариантик который нам показывали на консультации (весовая функция синий синус)

## Сначала учимся интегрировать $\int_{0}^{\pi }x^n\cdot sin(x)$

In [112]:
I=[0,1,2,3]

В функцию засуну лямбда функцию, которая возвращает $x^n \cdot \sin(x)$ числа и прошу проинтегрировать от нуля до пи, затем добавляю в наш массив чтобы потом найти коэффициенты для Гауса картофеля

In [115]:
I[0]=scipy.integrate.quad(lambda x:np.sin(x),0,np.pi)[0]
I[0]

2.0

На семинаре 2

In [117]:
I[1]=scipy.integrate.quad(lambda x: x*np.sin(x),0,np.pi)[0]
I[1]

3.141592653589793

На семинаре $\pi$

In [118]:
I[2]=scipy.integrate.quad(lambda x: x*x*np.sin(x),0,np.pi)[0]
I[2]

5.869604401089359

На семинаре $\pi^2-4$

In [102]:
np.pi*np.pi-4

5.869604401089358

Совпадает. Считаем последний интеграл :

In [120]:
I[3]=scipy.integrate.quad(lambda x: x*x*x*np.sin(x),0,np.pi)[0]
I[3]

12.15672075876106

In [104]:
np.pi*np.pi*np.pi-6*np.pi

12.156720758761058

Блин внатуре реально магические приколы какие-то

Итого

In [121]:
I

[2.0, 3.141592653589793, 5.869604401089359, 12.15672075876106]

## Теперь попробуем влезть в наш солвер, солвать будем scipy.fsolve(бебебе)

In [128]:
def func(x):
    return [x[0]+x[1]-I[0],
            x[0]*x[2]+x[1]*x[3]-I[1],
            x[0]*x[2]*x[2]+x[1]*x[3]*x[3]-I[2],
            x[0]*x[2]*x[2]*x[2]+x[1]*x[3]*x[3]*x[3]-I[3]
           ]

In [131]:
scipy.optimize.fsolve(func,[0,0,0,0])

array([ 1.39127708,  0.60872472, -0.112394  ,  0.19306171])

## Это говно не работает, он вычматами считает, скажите пж что здесь не так, я здесь под переменными имею ввиду $\omega_0=x[0],\omega_1=x[1],x_0=x[2],x_1=x[3]$